In [313]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import seaborn as sns
# importing alll the necessary packages to use the various classification algorithms
from sklearn.linear_model import LogisticRegression # for Logistic Regression Algorithm
from sklearn.cross_validation import train_test_split # to split the dataset for training and testing 
from sklearn.neighbors import KNeighborsClassifier # KNN classifier
from sklearn import svm # for suport vector machine algorithm
from sklearn import metrics # for checking the model accuracy
from sklearn.tree import DecisionTreeClassifier # for using DTA

In [314]:
import os
os.getcwd()

'C:\\Users\\MaryClare'

In [315]:
Train_digitsdf = pd.read_csv("digits_train.csv")
Test_digitsdf = pd.read_csv("digits_test.csv")

In [316]:
Train_digitsdf.head()

Unnamed: 0  0  1   2   3   4   5  6  7  8   ...    55  56  57  58  59  60  \
0           0  0  0   2  12   3   0  0  0  0   ...     0   0   0   1  15  16   
1           1  0  0  13  13  13  12  4  0  0   ...     0   0   1   9  14  15   
2           2  0  0   0  12   8   0  6  3  0   ...     0   0   0   0  12   6   
3           3  0  0   1  11  10   0  0  0  0   ...     0   0   0   0  13   8   
4           4  0  0   1  10  14  13  2  0  0   ...     0   0   0   0  14   2   

   61  62  63  labels  
0  13   4   0       6  
1   4   0   0       5  
2   0   0   0       4  
3   0   0   0       9  
4   0   0   0       7  

[5 rows x 66 columns]

In [317]:
Train_digitsdf.drop('Unnamed: 0', axis = 1, inplace=True)#dropped the first column as its unnecesary

In [318]:
Test_digitsdf.head()

Unnamed: 0  0  1   2   3   4   5  6  7  8 ...  54  55  56  57  58  59  60  \
0           0  0  0  12  16   9   0  0  0  0 ...  16   0   0   1  10  15  16   
1           1  0  2  11  16   5   0  0  0  0 ...  10   0   0   2  12  13  12   
2           2  0  0   9  15  14   1  0  0  0 ...  12   0   0   0   9  16  16   
3           3  0  0   6  15  16  12  1  0  0 ...   6   0   0   0   6  14  12   
4           4  0  0  11  13  12  12  3  0  0 ...   0   0   0   1  12  16  12   

   61  62  63  
0  16  10   0  
1  10   1   0  
2  16   6   0  
3   4   0   0  
4   2   0   0  

[5 rows x 65 columns]

In [240]:
Train_digitsdf.head()

0  1   2   3   4   5  6  7  8  9   ...    55  56  57  58  59  60  61  62  \
0  0  0   2  12   3   0  0  0  0  0   ...     0   0   0   1  15  16  13   4   
1  0  0  13  13  13  12  4  0  0  1   ...     0   0   1   9  14  15   4   0   
2  0  0   0  12   8   0  6  3  0  0   ...     0   0   0   0  12   6   0   0   
3  0  0   1  11  10   0  0  0  0  0   ...     0   0   0   0  13   8   0   0   
4  0  0   1  10  14  13  2  0  0  0   ...     0   0   0   0  14   2   0   0   

   63  labels  
0   0       6  
1   0       5  
2   0       4  
3   0       9  
4   0       7  

[5 rows x 65 columns]

In [241]:
Train_digitsdf['0'].sum() #I will avoid the first row in the classifier becasue it is just Zeros

0

In [242]:
Train_digitsdf.describe()

0            1            2            3           4           5  \
count  4000.0  4000.000000  4000.000000  4000.000000  4000.00000  4000.00000   
mean      0.0     0.290000     5.392750    11.865750    11.56875     5.63025   
std       0.0     0.873837     4.620859     4.208819     4.47239     5.63076   
min       0.0     0.000000     0.000000     0.000000     0.00000     0.00000   
25%       0.0     0.000000     1.000000    10.000000     9.00000     0.00000   
50%       0.0     0.000000     5.000000    13.000000    13.00000     4.00000   
75%       0.0     0.000000     9.000000    15.000000    15.00000    10.00000   
max       0.0     8.000000    16.000000    16.000000    16.00000    16.00000   

                 6            7            8            9     ...       \
count  4000.000000  4000.000000  4000.000000  4000.000000     ...        
mean      1.369000     0.132750     0.003250     1.956250     ...        
std       3.343222     0.992912     0.072393     3.076882     ...        
min       0.000000     0.000000     0.000000     0.000000     ...        
25%       0.000000     0.000000     0.000000     0.000000     ...        
50%       0.000000     0.000000     0.000000     0.000000     ...        
75%       0.000000     0.000000     0.000000     3.000000     ...        
max      16.000000    15.000000     2.000000    16.000000     ...        

                55           56           57           58           59  \
count  4000.000000  4000.000000  4000.000000  4000.000000  4000.000000   
mean      0.167750     0.000500     0.279250     5.762000    12.045000   
std       0.854572     0.022358     0.925194     4.982375     4.292678   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     1.000000    10.000000   
50%       0.000000     0.000000     0.000000     5.000000    13.000000   
75%       0.000000     0.000000     0.000000    10.000000    16.000000   
max      13.000000     1.000000    10.000000    16.000000    16.000000   

                60           61           62           63       labels  
count  4000.000000  4000.000000  4000.000000  4000.000000  4000.000000  
mean     11.524750     6.664000     2.069250     0.258500     4.543750  
std       4.976754     5.779702     3.995178     1.436556     2.869868  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       9.000000     0.000000     0.000000     0.000000     2.000000  
50%      13.000000     6.000000     0.000000     0.000000     5.000000  
75%      16.000000    12.000000     2.000000     0.000000     7.000000  
max      16.000000    16.000000    16.000000    16.000000     9.000000  

[8 rows x 65 columns]

In [384]:
Train_digitsdf[4, 3:4]

array([1], dtype=int64)

# Classification

## Decision Trees

In [323]:
Train_digitsdf = pd.read_csv("digits_train.csv").values
Test_digitsdf = pd.read_csv("digits_test.csv").values

In [324]:
#Training Data 
clf = DecisionTreeClassifier()
xtrain = Train_digitsdf[0:3000:, 1:65]
ytrain = Train_digitsdf[0:3000:, -1]

In [325]:
clf.fit(xtrain, ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [326]:
#Validation Data
xtest = Train_digitsdf[3000:, 1:65]
Actual_Labels = Train_digitsdf[3000:, -1]

In [327]:
y_predict = clf.predict(xtest)
len(Actual_Labels)

1000

In [328]:
count = 0
for i in range(0, 1000):
    count += 1 if y_predict[i]==Actual_Labels[i] else 0
print("The prediction accuracy for Decision tree is=", (count/1000)*100,"%")

The prediction accuracy for Decision tree is= 87.5 %


In [329]:
print ("The prediction accuracy for Decision tree is = ", metrics.accuracy_score(y_predict, Actual_Labels))

The prediction accuracy for Decision tree is =  0.875


## K Nearest Neighbors

In [330]:
model = KNeighborsClassifier(n_neighbors=3) # this examines 3 neighbors for putting the data into class
model.fit(xtrain, ytrain)
y_predict = model.predict(xtest)
print('The prediction accuracy for KNN is: ', metrics.accuracy_score(y_predict, Actual_Labels))

The prediction accuracy for KNN is:  0.982


## Logistics Regression

In [331]:
model = LogisticRegression()
model.fit(xtrain, ytrain)
y_predict = model.predict(xtest)
print('The prediction accuracy for LG is: ', metrics.accuracy_score(y_predict, Actual_Labels))

The prediction accuracy for LG is:  0.957


## Support Vector Machines

model = svm.SVC()
model = SVC(kernel= 'linear', C=1E10)
model.fit(xtrain, ytrain)
y_predict = model.predict(xtest)
print('The prediction accuracy for svm is: ', metrics.accuracy_score(y_predict, Actual_Labels))

## Neural Network Classifier 

In [332]:
clf = clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                 hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(xtrain, ytrain)
y_predict = clf.predict(xtest)
print('The prediction accuracy for Neural Net is: ', metrics.accuracy_score(y_predict, Actual_Labels))


The prediction accuracy for Neural Net is:  0.662


# Prediction to the Test Data Set 

In [358]:
# KNN was choosen to predict value as it ranked highest in accuracy compared to any other model.
#Note that Decision Trees and Neural Nets model performed relatively poorly
#Test Data 
x_test = Test_digitsdf[0:1620, 1:65]
clf = KNeighborsClassifier(n_neighbors=3) # this examines 3 neighbors for putting the data into class
clf.fit(xtrain, ytrain)
grand_predict = model.predict(x_test)
grand_predict

array([6, 3, 9, ..., 0, 6, 2], dtype=int64)

In [359]:
len(grand_predict)

1620

In [334]:
Train_digitsdf.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [370]:
len(Test_digitsdf)

1620

In [374]:
Index = Test_digitsdf[:,0]
Index

array([   0,    1,    2, ..., 1617, 1618, 1619], dtype=int64)

In [369]:
len(Index)

1620

In [377]:
R = pd.DataFrame(grand_predict)

In [378]:
R

0
0     6
1     3
2     9
3     2
4     5
5     7
6     6
7     8
8     1
9     0
10    2
11    2
12    9
13    2
14    3
15    0
16    9
17    9
18    5
19    2
20    7
21    2
22    4
23    1
24    0
25    4
26    6
27    1
28    7
29    7
...  ..
1590  1
1591  9
1592  6
1593  1
1594  8
1595  7
1596  0
1597  7
1598  0
1599  7
1600  3
1601  0
1602  5
1603  2
1604  0
1605  1
1606  0
1607  5
1608  5
1609  9
1610  5
1611  0
1612  4
1613  3
1614  1
1615  3
1616  0
1617  0
1618  6
1619  2

[1620 rows x 1 columns]

In [383]:
R.to_excel('results.xlsx')